(lang dune 3.20)

(name moepwn)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "nullenvk <nullenvk@protonmail.com>")

(maintainers "nullenvk <nullenvk@protonmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name moepwn)
 (synopsis "A toy toolkit for binary exploitation")
 (description "A simple, toy OCaml toolkit for binary exploitation")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
